### ISSUE TITLE
user change their shell

### ISSUE THREAD

**Issue by suker413** [ghantoos/lshell#104] opened 2015-07-07 04:20 UTC
hi,ghantoos，for example:

liangsh@dev2:~$ ?
clear exit help history lpath lsudo tttt vi

root@dev2:/home/liangsh# cat tttt
#!/bin/bash
echo "change shell to bash"

liangsh@dev2:~$ w
*** forbidden command: w

when modify tttt like this:

liangsh@dev2:~$ vi tttt
liangsh@dev2:/home/liangsh# cat tttt
#!/bin/bash
echo "change shell to bash"
/bin/bash

liangsh@dev2:~$ tttt
change shell to bash
liangsh@dev2:~$ w
11:51:23 up 24 min, 3 users, load average: 0.00, 0.01, 0.02
USER TTY FROM LOGIN@ IDLE JCPU PCPU WHAT
root pts/0 172.16.201.1 11:27 3:47 0.12s 0.12s -bash
liangsh pts/1 172.16.201.1 11:43 3.00s 0.04s 0.00s w
root pts/2 172.16.201.1 11:35 11:15 0.08s 0.08s -bash

**Comment by ghantoos** [comment] 2015-07-07 05:12
Duplicate of #101. Closing.

**Closed by ghantoos** 2015-07-07 05:12 UTC
