### ISSUE TITLE
lshell close Connection after one command

### ISSUE THREAD

**Issue by LamesSeulJames** [ghantoos/lshell#92] opened 2014-11-20 18:05 UTC
i'm running on FreeBSD 10.0-RELEASE with lshell-0.9.16 package. If i hit 'ls' , result is ok, but if i hit 'ls' one more, lshell close connection with message "Connection to FQDN closed."

it's the same problem with other allowed command.

But if i hit '?' several, connection still up.

i activate log, but no file create.

i have make a mistake ?

could you help me please ?

you can read my conf on http://pastebin.com/m4gVMdyd

**Comment by ghantoos** [comment] 2015-07-05 04:42
Hi,

Do you have the same result when when launching lshell locally?

I don't currently have a FreeBSD to test this. It works fine on my debian.

(sorry for the delayed response)

**Comment by berzia** [comment] 2016-03-11 13:05
Hi,

I have the same problem. I'm running on FreeBSD 10.2-RELEASE with lshell-0.9.16 and when I hit one command, Lshell close connection without any message. I have the same problem when I use it in local except that Lshell close with this message " Suspended (tty output)"

**Comment by xlr-8** [comment] 2016-03-14 16:07
@LamesSeulJames in your configuration apparently you specified no file, nor log level, which might explain why you don't have a logfile.
@berzia Could you configure lshell to have a logfile with more output maybe?

It might tell more why is the connection being closed.

**Comment by ghantoos** [comment] 2016-03-15 03:41
I was able to reproduce the bug on a vagrant FreeBSD 10.2-RELEASE box, using the available lshell package. I discovered this is due to a commit that was reverted that added ```set -m``` to all the executed commands (https://github.com/ghantoos/lshell/commit/b4f48136aee01bf387915e4b0fc750ee655b3afe).

There are two possible solutions:
  - revert the patch locally
  - use the latest version of lshell

1) To patch the file on your system (tested on my FreeBSD vm):
```
sed -i.bak 's/set -m; //' /usr/local/lib/python2.7/site-packages/lshell/shellcmd.py
```

2) The problem does not appear in the latest version of lshell. You can try it the following (using bash):
```
git clone https://github.com/ghantoos/lshell.git
cd lshell/
sed -i.bak 's,/usr/bin/env python,/usr/local/bin/python2.7,' bin/lshell
export PYTHONPATH=$PWD
./bin/lshell
```

Do you confirm either of these options solve your issue?

**Comment by ghantoos** [comment] 2016-03-15 03:59
I have filed a bug on the FreeBSD bugzilla to have this corrected in the official package: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208003

**Comment by berzia** [comment] 2016-03-15 08:28
Hi,

thank you for your quick responses . Your first solution, Ghantoos, works perfectly.

Thanks again.

**Comment by ghantoos** [comment] 2016-03-15 13:01
@berzia great! :)

I wil close this bug, as a bug report has been filed for FreeBSD to correct this in their official package. Thanks for re-opening this report.

**Closed by ghantoos** 2016-03-15 13:01 UTC
Labels: bug, help/support
