### ISSUE TITLE
lshell and cpanel

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#116] opened 2015-12-04 09:23 UTC
Hello, I make tests using lshell on server with cPanel. I want to use all cPanel scripts. For example:

```
/usr/local/cpanel/scripts
/scripts
```

I set this paths in allowed_cmd_path but this does't work. Can you give me a suggestion?

The same problem is with dir /usr/local/apache/bin for example.

**Comment by lmarkov** [comment] 2016-01-19 15:38
I saw that evething works but there is no need to write /scripts in front of the script name as usual.

**Comment by ghantoos** [comment] 2016-01-19 18:38
:+1:

**Comment by lmarkov** [comment] 2016-03-17 10:19
Hello, 
I try to add scripts from /etc/init.d/ but when I added this directory or the full path /etc/rc.d/init.d to allowed_cmd_path there is no result.

The only way I can execute a script from this location is to add the name of the script into allowed commands and put alias to 'command':'/etc/rc.d/init.d/command'.

Can you suggest me another solution?

**Comment by ghantoos** [comment] 2016-03-17 15:33
@lmarkov adding ```/etc/rc.d/init.d ``` will make all the commands located in this folder available, without the ```/etc/rc.d/init.d``` appended. For example: ```/etc/rc.d/init.d/openvpn start```, becomes ```openvpn start```.

Otherwise, you will have to add the script full paths in the ```allowed``` list. This will need to be done one-by-one.

**Comment by ghantoos** [comment] 2016-03-19 22:15
@lmarkov I'm closing this issue, please reopen it if the answer above is not what you were looking for.

**Closed by ghantoos** 2016-03-19 22:15 UTC

**Comment by lmarkov** [comment] 2016-03-21 12:21
I made a test and everything looks like you said but for example:

```
:~$ cdp-agent status
lshell: status: No such file or directory
```
If I add alias 
```
'cdp-agent':'/etc/rc.d/init.d/cdp-agent'
```
it works:
```
:~$ cdp-agent status
/etc/rc.d/init.d/cdp-agent status: cdp (pid 6734) running
```

**Comment by ghantoos** [comment] 2016-03-21 20:36
I was not able to reproduce your bug:
```
ghantoos:~$ networking
Usage: /etc/init.d/networking {start|stop|reload|restart|force-reload}
```

This invokes ```/etc/init.d/networking start```.

Good to know that the alias corrects your use-cases. Thanks for sharing this.
