### ISSUE TITLE
lshell .profile to run command on user login?

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#77] opened 2014-05-30 15:39 UTC
Does lshell support a file such as the .bash_profile where one can run commands when the user logs in? I would like to run the following command as soon as the user logs in:

eval "$(rbenv init -)"

**Comment by ghantoos** [comment] 2016-02-20 21:25
Closing, duplicate of #89

**Closed by ghantoos** 2016-02-20 21:25 UTC
Labels: wishlist
